### PR TITLE
Finish Unbag Merge

### PR DESCRIPTION
**Pull request by CheezBallzPi**
Merge this once when unbag finishes. It should include all the working code and stuff.

### CODE REVIEW

**Review by jacksondm33 — DISMISSED** [review]

**Comment by CheezBallzPi** [comment]
Wait, don't merge it yet. Wait until afterwards

**Comment by jacksondm33** [comment]
Linear vs Logistic Normalization:
https://www.desmos.com/calculator/ajahqbr1j2

**Comment by CheezBallzPi** [comment]
Yes. Totally down for Logistic.

**Comment by jacksondm33** [comment]
I kept both options in drivetrain. I didn't switch them yet.

**Pull request closed without merging**
