### PR TITLE
Competition code

### PR DESCRIPTION
**Pull request by jacksondm33**
### Main focus of this PR
Merge working competition code to master.

### CODE REVIEW

**Comment by CheezBallzPi** [comment]
Does this include stuff from the game laptop?

**Comment by CheezBallzPi** [comment]
Doesn't look like it does.

**Comment by jacksondm33** [comment]
Some of it at least. I thought you pushed all the changes?

**Comment by jacksondm33** [comment]
We should have backup code in case some of my newer changes create problems.

**Comment by CheezBallzPi** [comment]
Agreed. We are still missing the second half of the code, mainly the working auton, I believe.

**Comment by CheezBallzPi** [comment]
We're dropping this PR. Incomplete code, and the rest of it is squished into some other commit. @jacksondm33: If you agree, close this.

**Pull request closed without merging**
